#ifndef _BMP_ERRORS_H_
#define _BMP_ERRORS_H_

typedef enum {
    READ_OK = 0,
    READ_H_CORRUPTION,
    READ_H_INVALID_SIGNATURE,
    READ_H_INVALID_BMP_FILE_SIZE,
    READ_H_INVALID_RESERVED_BITS,
    READ_H_INVALID_BMP_OFFSET,
    READ_I_CORRUPTION,
    READ_I_INVALID_BMP_SIZE,
    READ_I_INVALID_WIDTH,
    READ_I_INVALID_HEIGHT,
    READ_I_INVALID_PLANES,
    READ_I_INVALID_BCOUNT,
    READ_I_UNSUPPORTED_BCOUNT,
    READ_I_INVALID_COMPRESSION,
    READ_I_UNSUPPORTED_COMPRESSION,
    READ_P_CORRUPTED
} read_status_t;

typedef enum {
    WRITE_OK = 0,
    WRITE_ERROR,
    WRITE_CLOSE_ERROR
} write_status_t;
#endif
